export const FETCH_SUBJECTS = "FETCH_SUBJECTS";
export const SUBJECT_STARRED = "SUBJECT_STARRED";
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const CREATE_COMMENTS = "CREATE_COMMENTS";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
